language: ruby
rvm:
  - 2.3.3
  - 2.2.2

gemfile:
  - gemfiles/rails_5.0.1.gemfile
  - gemfiles/rails_4.1.0.gemfile

addons:
  code_climate:
    repo_token: $CODE_CLIMATE_REPO_TOKEN

after_success:
  - bundle exec codeclimate-test-reporter
